name: The CD file

on:
    workflow_run:
        workflows: [The CI file]
        types:
            - completed

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Set up azure 
              uses: azure/webapps-deploy@85270a1854658d167ab239bce43949edb336fa7c
              with:
                app-name: autodeploy-testing
                publish-profile:  ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
                images: index.docker.io/oadeniran/quote-gen:latest2