name: The CI file

on:
    workflow_dispatch:

    push:
        branches:
            - main

jobs:
    Containerize-job:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Login to docker
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_HUB_USER }}
                password: ${{ secrets.DOCKER_HUB_PAT }}
            
            - name: Setup docker build
              uses: docker/setup-buildx-action@v3 

            - name: Containerize and push the app
              uses: docker/build-push-action@v5
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: ${{ secrets.DOCKER_HUB_USER }}/quote-gen:latest
    




